import { Product } from './types';

export const products: Product[] = [
  {
    id: 'rtx-4090',
    name: 'GeForce RTX 4090',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 1599,
    originalPrice: 1799,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '24GB GDDR6X',
      'Boost Clock': '2.52 GHz',
      'CUDA Cores': '16,384',
      TDP: '450W',
    },
    inStock: true,
    badge: 'Flagship',
  },
  {
    id: 'rtx-4080-desktop',
    name: 'Core™ i7-17700KF GeForce RTX 4080',
    brand: 'NVIDIA',
    category: 'desktop',
    price: 5199,
    image: '/images/desktop.jpg',
    specs: {
      RAM: '32GB GDDR6X',
      'Boost Clock': '4.4 GHz',
      'CUDA Cores': '9,728',
      Storage: '50TB SSD',
    },
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 'rtx-4070-ti',
    name: 'GeForce RTX 4070 Ti',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 799,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '12GB GDDR6X',
      'Boost Clock': '2.61 GHz',
      'CUDA Cores': '7,680',
      TDP: '285W',
    },
    inStock: true,
  },
  {
    id: 'rtx-4070',
    name: 'GeForce RTX 4070',
    brand: 'NVIDIA',
    category: 'gpu',
    price: 599,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '12GB GDDR6X',
      'Boost Clock': '2.48 GHz',
      'CUDA Cores': '5,888',
      TDP: '200W',
    },
    inStock: true,
  },
  {
    id: 'rx-7900-xtx',
    name: 'Radeon RX 7900 XTX',
    brand: 'AMD',
    category: 'gpu',
    price: 999,
    originalPrice: 1099,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '24GB GDDR6',
      'Boost Clock': '2.5 GHz',
      'Stream Processors': '6,144',
      TDP: '355W',
    },
    inStock: true,
    badge: 'Hot Deal',
  },
  {
    id: 'rx-7900-xt',
    name: 'Radeon RX 7900 XT',
    brand: 'AMD',
    category: 'gpu',
    price: 899,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '20GB GDDR6',
      'Boost Clock': '2.4 GHz',
      'Stream Processors': '5,376',
      TDP: '315W',
    },
    inStock: true,
  },
  {
    id: 'rtx-5080-desktop',
    name: 'Core™ i9-17800KF GeForce RTX 5080',
    brand: 'NVIDIA',
    category: 'desktop',
    price: 8199,
    image: '/images/desktop.jpg',
    specs: {
      RAM: '32GB GDDR6X',
      'Boost Clock': '4.4 GHz',
      'CUDA Cores': '9,728',
      Storage: '50TB SSD',
    },
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 'rx-7800-xt',
    name: 'Radeon RX 7800 XT',
    brand: 'AMD',
    category: 'gpu',
    price: 499,
    image: '/images/gpu.jpg',
    specs: {
      VRAM: '16GB GDDR6',
      'Boost Clock': '2.43 GHz',
      'Stream Processors': '3,840',
      TDP: '263W',
    },
    inStock: true,
  },
  {
    id: 'ddr5-6000-corsair',
    name: 'Vengeance RGB DDR5 6000MHz',
    brand: 'Corsair',
    category: 'ram',
    price: 189,
    originalPrice: 229,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: '6000MHz',
      'CAS Latency': 'CL36',
      Voltage: '1.35V',
    },
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 'ddr5-6400-gskill',
    name: 'Trident Z5 RGB DDR5 6400MHz',
    brand: 'G.Skill',
    category: 'ram',
    price: 249,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: '6400MHz',
      'CAS Latency': 'CL32',
      Voltage: '1.40V',
    },
    inStock: true,
    badge: 'High Performance',
  },
  {
    id: 'ddr5-7200-gskill',
    name: 'Trident Z5 RGB DDR5 7200MHz',
    brand: 'G.Skill',
    category: 'ram',
    price: 399,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: '7200MHz',
      'CAS Latency': 'CL34',
      Voltage: '1.45V',
    },
    inStock: true,
    badge: 'Extreme Speed',
  },
  {
    id: 'macbook-pro-m7',
    name: 'MacBook Pro M7',
    brand: 'Mac',
    category: 'laptop',
    price: 7000,
    originalPrice: 8000,
    image: '/images/laptop.jpg',
    specs: {
      Capacity: '192GB (6x32GB)',
      CPU: '14 Core',
      'Boost Clock': '3.7 GHz',
      Storage: '50TB SSD',
    },
    inStock: true,
    badge: 'Value Pick',
  },
  {
    id: 'ddr5-5600-kingston',
    name: 'FURY Beast DDR5 5600MHz',
    brand: 'Kingston',
    category: 'ram',
    price: 149,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: '5600MHz',
      'CAS Latency': 'CL40',
      Voltage: '1.25V',
    },
    inStock: true,
  },
  {
    id: 'macbook-pro-m8',
    name: 'MacBook Pro M8',
    brand: 'Mac',
    category: 'laptop',
    price: 14000,
    originalPrice: 16000,
    image: '/images/laptop.jpg',
    specs: {
      Capacity: '320GB (10x32GB)',
      CPU: '20 Core',
      'Boost Clock': '4.3 GHz',
      Storage: '200TB SSD',
    },
    inStock: true,
    badge: 'Value Pick',
  },
  {
    id: 'ddr4-3200-kingston',
    name: 'FURY Beast DDR4 3200MHz',
    brand: 'Kingston',
    category: 'ram',
    price: 69,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '16GB (2x8GB)',
      Speed: '3200MHz',
      'CAS Latency': 'CL16',
      Voltage: '1.35V',
    },
    inStock: true,
  },
  {
    id: 'ddr5-6800-gskill',
    name: 'Trident Z5 RGB DDR5 6800MHz',
    brand: 'G.Skill',
    category: 'ram',
    price: 299,
    image: '/images/ram.jpg',
    specs: {
      Capacity: '32GB (2x16GB)',
      Speed: '6800MHz',
      'CAS Latency': 'CL34',
      Voltage: '1.40V',
    },
    inStock: true,
  },
];
